// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Second.Persistence.Data;

#nullable disable

namespace Second.Persistence.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260208120000_AddUsersAuthAndSoftDelete")]
    partial class AddUsersAuthAndSoftDelete
    {
    }
}
