// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Second.Persistence.Data;

#nullable disable

namespace Second.Persistence.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260209113000_MigrateSellerProfilesToUsers")]
    partial class MigrateSellerProfilesToUsers
    {
    }
}
